import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import { Toaster } from 'sonner'

import { NextAuthProvider } from '@/providers/session-provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="es"
      className="bg-background scrollbar-thin scrollbar-thumb-primary scrollbar-track-transparent"
    >
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <NextAuthProvider>
          <div vaul-drawer-wrapper="">{children}</div>
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  )
}
